name: Firebase Deploy

on:
  push:
    branches:
      - main # Or your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # ... other steps (install dependencies, build) ...

      - name: Deploy to Firebase
        uses: actions/github-script@v6
        with:
          script: |
            const core = require('@actions/core');
            const github = require('@actions/github');
            const fs = require('fs');

            // Get the API key from the secret
            const apiKey = core.getInput('API_KEY'); 

            // ... rest of your deployment script, using the apiKey ... 

      # ... other steps (e.g., add comment) ...

env:
  API_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }} 